### PR TITLE
bump and publish version 0.0.1

### PR DESCRIPTION
**Pull request by joewagner**
Cleaned up README.md, added standard dual license, and setup the version and tags to publish 0.0.1

### CODE REVIEW

**Review by sanderpick — APPROVED** [review]
really nice. @carsonfarmer can give me the tldr on why we also have apache license?

**Comment by carsonfarmer** [comment]
That dual license setup is starting to become standard practice in some OSS communities such as Rust and most of PLN/IPFS libraries. The reasoning stems (in some part) from issues with patent granting. The general description (stolen from the internet somewhere) is:

Requiring both MIT and Apache 2.0 as _inbound_ licenses for contributions means that anyone making a contribution is providing the Apache 2.0 patent grant. And then having MIT and Apache 2.0 as _outbound_ licenses means our libraries provide widespread compatibility with all sorts of other FOSS licenses, including GPLv2. Actually, we could just scrap the two and use something like https://opensource.org/licenses/BSDplusPatent instead, which looks quite good.

For further reference, here's an issue from the IPFS community that reflects the thinking around the dual licensing setup: https://github.com/ipfs/js-ipfs/issues/2624.

**Comment by sanderpick** [comment]
cool, thanks for the brain dump. sounds good to me.

**Comment by joewagner** [comment]
Should we switch the license here before publishing?

**Comment by sanderpick** [comment]
I think what you did looks good

**Pull request merged**
