### PR TITLE
Fix typos in README code examples

### PR DESCRIPTION
**Pull request by datadanne**

### CODE REVIEW

**Review by dtbuchholz — APPROVED** [review]
🤘

**Comment by datadanne** [comment]
I had to rebase the branch because something else got merged, can you re-approve it @dtbuchholz? :pray:

**Review by dtbuchholz — APPROVED** [review]
approved!

**Comment by datadanne** [comment]
> approved!

lol my commit isn't signed because I used the github UI to rebase.. rebasing again, will need a third approval I think!

**Pull request merged**
